### ISSUE TITLE
More ClinVar accessions incorrectly persisted

### ISSUE THREAD

**Issue by bpow** [jdr0887/canvas-primer#3]
RCV000207071 should be an insertion of an A, but gets persisted as delins A>GG

**Comment by bpow** [comment]
RCV000485317 should be insertion of a CG, but gets persisted as a snp A>C

**Comment by bpow** [comment]
It might be easier/more consistent/less code to persist the clinvar variants using positionVCF, referenceAlleleVCF and alternateAlleleVCF when available.

**Comment by jdr0887** [comment]
I think I got these, there is a test case to write out the LocatedVariant for each of these accessions & they all look good.
